# Site settings
title: "Ederpesca y Derivados SL"
description: >
  Lo mejor del mar en su cocina. Nos encargamos de acercaros a vuestras mesas
  el mejor bacalao desalado.

maintitle:
  es: "Ederpesca: Lo mejor del mar en su cocina"
  eu: "Ederpesca: Lo mejor del mar en su cocina"
  en: "Ederpesca: Lo mejor del mar en su cocina"
  fr: "Ederpesca: Lo mejor del mar en su cocina"
  it: "Ederpesca: Lo mejor del mar en su cocina"
subtitle:
  es: Nos encargamos de acercaros a vuestras mesas el mejor bacalao.
  eu: Nos encargamos de acercaros a vuestras mesas el mejor bacalao EU.
  en: Nos encargamos de acercaros a vuestras mesas el mejor bacalao EN.
  fr: Nos encargamos de acercaros a vuestras mesas el mejor bacalao FR.
  it: Nos encargamos de acercaros a vuestras mesas el mejor bacalao IT.

dir: Polígono Txirrita Maleo 5F
cp: 20100
city: Errenteria
provincia: Gipuzkoa
email: ederpesca@ederpesca.com
phone: 943 52 52 27


baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.ederpesca.com" # the base hostname & protocol for your site
enforce_ssl: www.ederpesca.com

facebook:
  app_id: Ederpesca-Y-Derivados-SL-953588594689790

logo: /images/ederpesca/logo.jpg

google_site_verification: kuuA5fqwf68iuMeu-teDya9Q8ef2eOIPDrsO4L3VQuc

index:
  en: en/
  es:
  eu: eu/
  fr: fr/
  it: it/

# Build settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js
  - travis.yml
  - build.sh

# Gems
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Colecciones
collections:
  slider:
  lineas:
  procesos:
  productos:
    output: true
    permalink: /:collection/:path/
  recetas:
    output: true
    permalink: /:collection/:path/
  nutricion:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: productos
    values:
      title: ""
      layout: producto
      hide_content: true
      resumen: ""
      seo:
        type: Product
      image:
        path:
      imagenes:
      texto: ""
      caracteristicas:
        - ""
      lang: es
      orden: 1
      shopify-id: 0
      shopify-handle: ""
  - scope:
      path: ""
      type: recetas
    values:
      layout: receta
      seo:
        type: Recipe
  - scope:
      path: ""
      type: nutricion
    values:
      layout: nutricion

  - scope:
      path: ""
      type: slider
    values:
      hide_content: true

shopify:
  domain: eder-pesca
  api-key: a91793d49f704556650ff83fcbede715
