# Site settings
maintitle:
  es: "Ederpesca: Lo mejor del mar en su cocina"
  eu: "Ederpesca: Lo mejor del mar en su cocina"
  en: "Ederpesca: Lo mejor del mar en su cocina"
  fr: "Ederpesca: Lo mejor del mar en su cocina"
  it: "Ederpesca: Lo mejor del mar en su cocina"
subtitle:
  es: Nos encargamos de acercaros a vuestras mesas el mejor bacalao.
  eu: Nos encargamos de acercaros a vuestras mesas el mejor bacalao EU.
  en: Nos encargamos de acercaros a vuestras mesas el mejor bacalao EN.
  fr: Nos encargamos de acercaros a vuestras mesas el mejor bacalao FR.
  it: Nos encargamos de acercaros a vuestras mesas el mejor bacalao IT.

dir: Polígono Txirrita Maleo 5F
cp: 20100
city: Errenteria
provincia: Gipuzkoa
email: ederpesca@ederpesca.com
phone: 943 52 52 27

description:
  es: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  eu: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  en: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  fr: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  it: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ederpesca.com" # the base hostname & protocol for your site

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - node_modules
  - gulpfile.js

index:
  en: en/
  es:
  eu: eu/
  fr: fr/
  it: it/

facebook_username: Ederpesca-Y-Derivados-SL-953588594689790

# Build settings
markdown: kramdown
permalink: pretty

# Colecciones
collections:
  slider:
  lineas:
  procesos:
  productos:
    output: true
    permalink: /:collection/:path/
  recetas:
    output: true
    permalink: /:collection/:path/
  nutricion:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: productos
    values:
      title: ""
      layout: producto
      hide_content: true
      resumen: ""
      miniatura_path:
      imagenes:
      texto: ""
      caracteristicas:
        - ""
      lang: es
      orden: 1
      shopify-id: 0
      shopify-handle: ""
  - scope:
      path: ""
      type: recetas
    values:
      layout: receta
  - scope:
      path: ""
      type: nutricion
    values:
      layout: nutricion

  - scope:
      path: ""
      type: slider
    values:
      hide_content: true

shopify:
  domain: eder-pesca
  api-key: a91793d49f704556650ff83fcbede715
