# Site settings
title:
  es: "Ederpesca: Lo mejor del mar en su cocina"
  eu: "Ederpesca: Lo mejor del mar en su cocina"
  en: "Ederpesca: Lo mejor del mar en su cocina"
  fr: "Ederpesca: Lo mejor del mar en su cocina"
  it: "Ederpesca: Lo mejor del mar en su cocina"
subtitle:
  es: Nos encargamos de acercaros a vuestras mesas el mejor bacalao ES.
  eu: Nos encargamos de acercaros a vuestras mesas el mejor bacalao EU.
  en: Nos encargamos de acercaros a vuestras mesas el mejor bacalao.
  fr: Nos encargamos de acercaros a vuestras mesas el mejor bacalao FR.
  it: Nos encargamos de acercaros a vuestras mesas el mejor bacalao FR.

dir: Polígono Manteo Txirrita 5F
cp: 20100
city: Errenteria
provincia: Gipuzkoa
email: ederpesca@ederpesca.com 
phone: 943 52 52 27
fax: 943 00 00 01

description:
  es: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  eu: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  en: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  fr: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
  it: > # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ederpesca.com" # the base hostname & protocol for your site

index:
  en: en/
  es: 
  eu: eu/
  fr: fr/
  it: it/

facebook_username: Ederpesca-Y-Derivados-SL-953588594689790

# Build settings
markdown: kramdown
permalink: pretty

# Colecciones
collections:
  slider:
  lineas:
  procesos:
  productos:
    output: true
    permalink: /:collection/:path/
  recetas:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: productos
    values:
      layout: producto
      hide_content: true
      nombre: ""
      resumen: ""
      miniatura_path: ""
      imagenes:
      texto: ""
      caracteristicas:
      lang: "es"
      orden: 1
      shopify-id:
      shopify-handle: ""
  - scope:
      path: ""
      type: recetas
    values:
      layout: receta
  - scope:
      path: ""
      type: slider
    values:
      hide_content: true

shopify:
  domain: eder-pesca
  api-key: a91793d49f704556650ff83fcbede715
